name: Build and publish environments to GHCR

on:
  # push:
  #   branches: ['main']
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-image:
    strategy:
      matrix:
        environments: [singleuser, test-image] # add folder names with environments here

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Docker Checkout
        uses: actions/checkout@v3

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2.5.0

      - name: Log in to the GH Container Registry
        id: login
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata for ${{ matrix.environments }}
        id: meta
        uses: docker/metadata-action@v4.3.0
        with:
          flavor: |
            latest=true
          tags: |
            type=sha
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ matrix.environments }}

      - name: Build and push ${{ matrix.environments }}
        id: build
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./${{ matrix.environments }}
          file: ./${{ matrix.environments }}/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
